---
services:
  stemnet:
    container_name: stemnet
    image: corey4005/stemnet-daily-files:latest
    environment:
      - TZ=America/Chicago
    restart: unless-stopped
    volumes:
      - ./daily_files:/root/stemnet/STEMNET-Daily-Files/daily_files/
      - ./logfiles:/root/stemnet/STEMNET-Daily-Files/logfiles/
      - ./climatology_files:/root/stemnet/STEMNET-Daily-Files/climatology_files/
