---
services:
  stemnet:
    container_name: stemnet
    image: corey4005/stemnet-daily-files:latest
    environment:
      - LOCAL_USER_ID=${LOCAL_USER_ID}
    volumes:
      - ./data_out:/home/user/stemnet/data_out/
    stdin_open: true
    tty: true 
    restart: unless-stopped
